# Generated by Django 5.1.4 on 2025-02-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('manage_all_courses', 'Управление всеми курсами'), ('manage_all_users', 'Управление всеми пользователями')]},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'permissions': [('enroll_in_course', 'Запись на курс'), ('manage_own_profile', 'Управление своим профилем')]},
        ),
    ]
